<a href="https://colab.research.google.com/github/Raghamala/INTERNSOFTcodefiles/blob/main/day6codefile.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [10]:
a = np.arange(10)
b = np.arange(14)

In [11]:
a
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [13]:
a = np.arange(14).reshape(2,7)
a

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13]])

In [16]:
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)
print(a.itemsize)
print(type(a))

2
(2, 7)
14
int64
8
<class 'numpy.ndarray'>


In [17]:
help(a)

Help on ndarray object:

class ndarray(builtins.object)
 |  ndarray(shape, dtype=float, buffer=None, offset=0,
 |          strides=None, order=None)
 |  
 |  An array object represents a multidimensional, homogeneous array
 |  of fixed-size items.  An associated data-type object describes the
 |  format of each element in the array (its byte-order, how many bytes it
 |  occupies in memory, whether it is an integer, a floating point number,
 |  or something else, etc.)
 |  
 |  Arrays should be constructed using `array`, `zeros` or `empty` (refer
 |  to the See Also section below).  The parameters given here refer to
 |  a low-level method (`ndarray(...)`) for instantiating an array.
 |  
 |  For more information, refer to the `numpy` module and examine the
 |  methods and attributes of an array.
 |  
 |  Parameters
 |  ----------
 |  (for the __new__ method; see Notes below)
 |  
 |  shape : tuple of ints
 |      Shape of created array.
 |  dtype : data-type, optional
 |      Any objec

In [18]:
b = np.array([1.0, 2.0, 3.0, 4.0])
print(b)
print(b.dtype)
print(type(b))

[1. 2. 3. 4.]
float64
<class 'numpy.ndarray'>


In [20]:
c = np.eye(12)
dtype = np.float64
c

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [23]:
d = np.linspace(-1,2,12,endpoint=True)
print(d)

[-1.         -0.72727273 -0.45454545 -0.18181818  0.09090909  0.36363636
  0.63636364  0.90909091  1.18181818  1.45454545  1.72727273  2.        ]


In [24]:
e=np.logspace(-1,2,15,endpoint=True,base=10)
print(e)

[  0.1          0.16378937   0.26826958   0.43939706   0.71968567
   1.17876863   1.93069773   3.16227766   5.17947468   8.48342898
  13.89495494  22.75845926  37.2759372   61.05402297 100.        ]


In [25]:
help(np.logspace)

Help on function logspace in module numpy:

logspace(start, stop, num=50, endpoint=True, base=10.0, dtype=None, axis=0)
    Return numbers spaced evenly on a log scale.
    
    In linear space, the sequence starts at ``base ** start``
    (`base` to the power of `start`) and ends with ``base ** stop``
    (see `endpoint` below).
    
    .. versionchanged:: 1.16.0
        Non-scalar `start` and `stop` are now supported.
    
    Parameters
    ----------
    start : array_like
        ``base ** start`` is the starting value of the sequence.
    stop : array_like
        ``base ** stop`` is the final value of the sequence, unless `endpoint`
        is False.  In that case, ``num + 1`` values are spaced over the
        interval in log-space, of which all but the last (a sequence of
        length `num`) are returned.
    num : integer, optional
        Number of samples to generate.  Default is 50.
    endpoint : boolean, optional
        If true, `stop` is the last sample. Otherwise, 

In [29]:
f=np.fromfunction(lambda i,j:i==j,(8,6),dtype=int)
f

array([[ True, False, False, False, False, False],
       [False,  True, False, False, False, False],
       [False, False,  True, False, False, False],
       [False, False, False,  True, False, False],
       [False, False, False, False,  True, False],
       [False, False, False, False, False,  True],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False]])

In [32]:
a=np.arange(12).reshape(3,4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [33]:
a*2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [34]:
a+a+a

array([[ 0,  3,  6,  9],
       [12, 15, 18, 21],
       [24, 27, 30, 33]])

In [35]:
a*a*a

array([[   0,    1,    8,   27],
       [  64,  125,  216,  343],
       [ 512,  729, 1000, 1331]])

In [36]:
b=a.transpose()
b

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [37]:
a@b

array([[ 14,  38,  62],
       [ 38, 126, 214],
       [ 62, 214, 366]])

In [39]:
print(a)
a.sum(axis=1)
a.sum()
print(a.min(),a.max())

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
0 11


In [40]:
b=a*np.pi/12.0
b

array([[0.        , 0.26179939, 0.52359878, 0.78539816],
       [1.04719755, 1.30899694, 1.57079633, 1.83259571],
       [2.0943951 , 2.35619449, 2.61799388, 2.87979327]])

In [41]:
c=np.cos(b)
c

array([[ 1.00000000e+00,  9.65925826e-01,  8.66025404e-01,
         7.07106781e-01],
       [ 5.00000000e-01,  2.58819045e-01,  6.12323400e-17,
        -2.58819045e-01],
       [-5.00000000e-01, -7.07106781e-01, -8.66025404e-01,
        -9.65925826e-01]])

In [42]:
d=b+c
d

array([[1.        , 1.22772521, 1.38962418, 1.49250494],
       [1.54719755, 1.56781598, 1.57079633, 1.57377667],
       [1.5943951 , 1.64908771, 1.75196847, 1.91386744]])

In [55]:
a=np.arange(300)
a
even=a[0:250:2]
print(even)

[  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70
  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100 102 104 106
 108 110 112 114 116 118 120 122 124 126 128 130 132 134 136 138 140 142
 144 146 148 150 152 154 156 158 160 162 164 166 168 170 172 174 176 178
 180 182 184 186 188 190 192 194 196 198 200 202 204 206 208 210 212 214
 216 218 220 222 224 226 228 230 232 234 236 238 240 242 244 246 248]


In [59]:
a=np.arange(5)
a

array([0, 1, 2, 3, 4])

In [46]:
a[1:4]

array([1, 2, 3])

In [47]:
a[:]

array([0, 1, 2, 3, 4])

In [60]:
a=np.arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [61]:
a[2,3]

13

In [62]:
a[0:1,0:2]

array([[0, 1]])

In [63]:
a[:,2]

array([ 2,  7, 12])

In [64]:
a=a.flatten()
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [67]:
for r in a:
  print(r)
  a=np.arange(12).reshape(3,4)
  print(a)


[0 1 2 3]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[4 5 6 7]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [68]:
for e in a.flat:
  print(e)

0
1
2
3
4
5
6
7
8
9
10
11


In [69]:
help(a.flatten())

Help on ndarray object:

class ndarray(builtins.object)
 |  ndarray(shape, dtype=float, buffer=None, offset=0,
 |          strides=None, order=None)
 |  
 |  An array object represents a multidimensional, homogeneous array
 |  of fixed-size items.  An associated data-type object describes the
 |  format of each element in the array (its byte-order, how many bytes it
 |  occupies in memory, whether it is an integer, a floating point number,
 |  or something else, etc.)
 |  
 |  Arrays should be constructed using `array`, `zeros` or `empty` (refer
 |  to the See Also section below).  The parameters given here refer to
 |  a low-level method (`ndarray(...)`) for instantiating an array.
 |  
 |  For more information, refer to the `numpy` module and examine the
 |  methods and attributes of an array.
 |  
 |  Parameters
 |  ----------
 |  (for the __new__ method; see Notes below)
 |  
 |  shape : tuple of ints
 |      Shape of created array.
 |  dtype : data-type, optional
 |      Any objec

In [70]:
a=np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [71]:
b=a
b is a

True

In [76]:
b.shape=(2, 6)
print(b)
a.shape

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


(2, 6)

In [78]:
b is a
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [80]:
a=np.arange(12)
c=a[:]
a.shape=(3,4)
print(a)
print(c)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [81]:
c[1]=-1
print(a)
print(c)

[[ 0 -1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0 -1  2  3  4  5  6  7  8  9 10 11]


In [82]:
d=c[3:8]
print(d)

[3 4 5 6 7]


In [83]:
d[:]=0

In [86]:
print(a)
print(d)
print(c)

[[ 0 -1  2  0]
 [ 0  0  0  0]
 [ 8  9 10 11]]
[0 0 0 0 0]
[ 0 -1  2  0  0  0  0  0  8  9 10 11]


In [87]:
print(c is a)
print(c.base is a)
print(c.flags.owndata)
print(a.flags.owndata)

False
True
False
True


In [88]:
d=a.copy()
d[:,:]=0.0
print(a)
print(d)

[[ 0 -1  2  0]
 [ 0  0  0  0]
 [ 8  9 10 11]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [89]:
a=np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [90]:
a[a>4]=0
a

array([[0, 1, 2, 3],
       [4, 0, 0, 0],
       [0, 0, 0, 0]])

In [96]:
print(a)
a[a==0]=-1
a

[[ 0  1  2  3]
 [ 0  0  0  0]
 [ 0  0 10 11]]


array([[-1,  1,  2,  3],
       [-1, -1, -1, -1],
       [-1, -1, 10, 11]])

In [92]:
a[a==0]=-1
a

array([[-1,  1,  2,  3],
       [ 4, -1, -1, -1],
       [-1, -1, -1, -1]])

In [93]:
a==-1

array([[ True, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [94]:
a=np.arange(12).reshape(3,4)
a[np.logical_and(a>3,a<=9)]=0.0
a

array([[ 0,  1,  2,  3],
       [ 0,  0,  0,  0],
       [ 0,  0, 10, 11]])

In [97]:
a>4

array([[False, False, False, False],
       [False, False, False, False],
       [False, False,  True,  True]])

In [98]:
M=25
N=32
xmin = ymin=0.0
xmax=ymax=1.0
x=np.linspace(xmin,xmax,M,endpoint=False)
y=np.linspace(ymin,ymax,N,endpoint=False)
print(x.shape)
print(y.shape)
y


(25,)
(32,)


array([0.     , 0.03125, 0.0625 , 0.09375, 0.125  , 0.15625, 0.1875 ,
       0.21875, 0.25   , 0.28125, 0.3125 , 0.34375, 0.375  , 0.40625,
       0.4375 , 0.46875, 0.5    , 0.53125, 0.5625 , 0.59375, 0.625  ,
       0.65625, 0.6875 , 0.71875, 0.75   , 0.78125, 0.8125 , 0.84375,
       0.875  , 0.90625, 0.9375 , 0.96875])

In [99]:
import time
import numpy as np
M=25
N=32
x=np.linspace(0.0,1.0,M,endpoint=False)
y=np.linspace(0.0,1.0,N,endpoint=False)


In [104]:
t0=time.time()
g=np.zeros((M,N))
for i in range(M):
  for j in range(N):
    g[i,j]=np.sin(2.0*np.pi*x[i]*y[j])
    print(g)
t1=time.time()
print("time elapsed:{}s".format(t1-t0))

Streaming output truncated to the last 5000 lines.
  0.         0.         0.         0.         0.         0.
  0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.        

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



Streaming output truncated to the last 5000 lines.
[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  7.85390089e-03  1.57073173e-02  2.35597648e-02
   3.14107591e-02  3.92598158e-02  4.71064507e-02  5.49501799e-02
   6.27905195e-02  7.06269859e-02  7.84590957e-02  8.62863658e-02
   9.41083133e-02  1.01924456e-01  1.09734311e-01  1.17537397e-01
   1.25333234e-01  1.33121339e-01  1.40901232e-01  1.48672434e-01
   1.56434465e-01  1.64186847e-01  1.71929100e-01  1.79660749e-01
   1.87381315e-01  1.950

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  7.85390089e-03  1.57073173e-02  2.35597648e-02
   3.14107591e-02  3.92598158e-02  4.71064507e-02  5.49501799e-02
   6.27905195e-02  7.06269859e-02  7.84590957e-02  8.62863658e-02
   9.41083133e-02  1.01924456e-01  1.09734311e-01  1.17537397e-01
   1.25333234e-01  1.33121339e-01  1.40901232e-01  1.48672434e-01
   1.56434465e-01  1.64186847e-01  1.71929100e-01  1.79660749e-01
   1.87381315e-01  1.95090322e-01  2.02787295e-01  2.10471760e-01
   2.1814

In [105]:
x2d,y2d=np.meshgrid(x,y,indexing="ij")
print(x2d[:,0])
print(x2d[0,:])
print(y2d[:,0])
print(y2d[0,:])


[0.   0.04 0.08 0.12 0.16 0.2  0.24 0.28 0.32 0.36 0.4  0.44 0.48 0.52
 0.56 0.6  0.64 0.68 0.72 0.76 0.8  0.84 0.88 0.92 0.96]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0.]
[0.      0.03125 0.0625  0.09375 0.125   0.15625 0.1875  0.21875 0.25
 0.28125 0.3125  0.34375 0.375   0.40625 0.4375  0.46875 0.5     0.53125
 0.5625  0.59375 0.625   0.65625 0.6875  0.71875 0.75    0.78125 0.8125
 0.84375 0.875   0.90625 0.9375  0.96875]


In [106]:
t0=time.time()
g2=np.sin(2.0*np.pi*x2d*y2d)
t1=time.time()
print("time elapsed:{}s".format(t1-t0))

time elapsed:0.0014278888702392578s


In [108]:
x=np.array([1,2,3,4])
x=np.array([4,3,2,1])
np.concatenate([y,x])

array([0.     , 0.03125, 0.0625 , 0.09375, 0.125  , 0.15625, 0.1875 ,
       0.21875, 0.25   , 0.28125, 0.3125 , 0.34375, 0.375  , 0.40625,
       0.4375 , 0.46875, 0.5    , 0.53125, 0.5625 , 0.59375, 0.625  ,
       0.65625, 0.6875 , 0.71875, 0.75   , 0.78125, 0.8125 , 0.84375,
       0.875  , 0.90625, 0.9375 , 0.96875, 4.     , 3.     , 2.     ,
       1.     ])

In [109]:
z=[9,5,4]
print(np.concatenate([x,y,z]))

[4.      3.      2.      1.      0.      0.03125 0.0625  0.09375 0.125
 0.15625 0.1875  0.21875 0.25    0.28125 0.3125  0.34375 0.375   0.40625
 0.4375  0.46875 0.5     0.53125 0.5625  0.59375 0.625   0.65625 0.6875
 0.71875 0.75    0.78125 0.8125  0.84375 0.875   0.90625 0.9375  0.96875
 9.      5.      4.     ]


In [111]:
grid=np.array([[10,20,30],
              [40,50,60]])

In [112]:
np.concatenate([grid,grid])

array([[10, 20, 30],
       [40, 50, 60],
       [10, 20, 30],
       [40, 50, 60]])

In [114]:
np.concatenate([grid,grid],axis=1)

array([[10, 20, 30, 10, 20, 30],
       [40, 50, 60, 40, 50, 60]])

In [116]:
x=[1,2,3,4,4,3,2,1,9,4,6]
x1,x2,x3,x4=np.split(x,[3,4,5])
print(x1,x2,x3,x4)

[1 2 3] [4] [4] [3 2 1 9 4 6]


In [117]:
grid=np.arange(25).reshape((5,5))
grid

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [118]:
left,right=np.hsplit(grid,[2])
print(left)
print(right)

[[ 0  1]
 [ 5  6]
 [10 11]
 [15 16]
 [20 21]]
[[ 2  3  4]
 [ 7  8  9]
 [12 13 14]
 [17 18 19]
 [22 23 24]]


In [119]:
x=np.arange(1,9)
print(x)
np.add.reduce(x)

[1 2 3 4 5 6 7 8]


36

In [120]:
np.multiply.reduce(x)

40320

In [121]:
np.add.accumulate(x)

array([ 1,  3,  6, 10, 15, 21, 28, 36])

In [122]:
np.multiply.accumulate(x)

array([    1,     2,     6,    24,   120,   720,  5040, 40320])